return PlaceObj('ModDef', {
	'title', "Internal Affairs",
	'description', "Internal Affairs\nv1.0 Dec 21st, 2018\nBy SkiRich",
	'image', "IALogo.png",
	'last_changes', "v1.0 Dec 21st, 2018",
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		"*.gitignore",
		"*Images/*",
	},
	'id', "ccPSpkd",
	'steam_id', "1596642938",
	'author', "SkiRich",
	'version', 9,
	'lua_revision', 238808,
	'code', {"Code/IA_1Init.lua","Code/IA_2Numbers.lua","Code/IA_3ModConfig.lua"},
	'saved', 1545379140,
	'screenshot1', "Images/IALogo.png",
	'screenshot2', "Images/IACure.png",
	'screenshot3', "Images/IAGameNotices.png",
	'screenshot4', "Images/IACommandCenter.png",
	'screenshot5', "Images/VoteUpApollo2.png",
	'TagGameplay', true,
	'TagTools', true,
	'TagOther', true,
})